# Generated by Django 5.0.3 on 2024-04-11 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('birth', models.DateTimeField()),
                ('intro', models.TextField()),
                ('elite', models.BooleanField(default=False)),
                ('live', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
